import { type AppType } from "next/app";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";

import { trpc } from "../utils/trpc";

import "../styles/globals.css";
import "../styles/adai-ui-dashboard-tailwind.css";
import "../styles/adai-ui-dashboard-tailwind.min.css";
import "../styles/nucleo-icons.css";
import "../styles/nucleo-svg.css";
import "../styles/perfect-scrollbar.css";
import "../styles/tooltips.css";
import Head from "next/head";
import Script from 'next/script'

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <>        
    <Head>
      <title>Create T3 App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />     
    </Head>     
    <Script src="https://kit.fontawesome.com/42d5adcbca.js" />
    
    <SessionProvider session={session}>
      <Component {...pageProps} />
    </SessionProvider>
  </>
  );
};

export default trpc.withTRPC(MyApp);
